version: "1.0"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    working_dir: /src
    container_name: fortunebank-api
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env
    volumes:
      - .:/src
